export const defaultValues = {
  title: "",
  image: null,
  price: 0,
  description: "",
  brand: "",
  model: "",
  color: null,
  size: null,
  ram: null,
  power: null,
  fps: null,
  soundOutput: null,
  screenSize: null,
  category: "",
  discount: 0,
  stock: 10,
};
