import { InferFormValues } from "@/app/_types/InferFormValuesType";
import { inputFieldType } from "@/app/_types/inputFieldType";
import { validations } from "./productsValidations";
import {
  getBrands,
  getCategories,
  getColors,
  getModels,
  getSizes,
} from "../services/productsAPIs";

export const formFields: inputFieldType<InferFormValues<typeof validations>>[] =
  [
    {
      type: "text",
      name: "title",
      lable: "Title",
      fullWidth: false,
      required: true,
      placeholder: "Enter product title",
    },
    {
      type: "dropdown",
      name: "category",
      lable: "Category",
      fullWidth: false,
      required: true,
      placeholder: "Enter product category",
      optionsMethod: getCategories,
    },

    {
      type: "dropdown",
      name: "brand",
      lable: "Brand",
      fullWidth: false,
      required: true,
      placeholder: "Enter brand name",
      optionsMethod: getBrands,
    },
    {
      type: "dropdown",
      name: "model",
      lable: "Model",
      fullWidth: false,
      required: true,
      placeholder: "Enter model name",
      optionsMethod: getModels,
    },
    {
      type: "text",
      name: "price",
      lable: "Price",
      fullWidth: false,
      required: true,
      placeholder: "Enter product price",
      isNumber: true,
    },
    {
      type: "text",
      name: "discount",
      lable: "Discount (%)",
      fullWidth: false,
      required: false,
      placeholder: "Enter discount (optional)",
      isNumber: true,
    },

    {
      type: "dropdown",
      name: "color",
      lable: "Color",
      fullWidth: false,
      required: false,
      placeholder: "Enter color (optional)",
      optionsMethod: getColors,
    },
    {
      type: "dropdown",
      name: "size",
      lable: "Size",
      fullWidth: false,
      required: false,
      placeholder: "Enter size (optional)",
      isNullable: true,
      optionsMethod: getSizes,
    },
    {
      type: "text",
      name: "ram",
      lable: "RAM (GB)",
      fullWidth: false,
      required: false,
      placeholder: "Enter RAM in GB (optional)",
      isNumber: true,
      isNullable: true,
    },
    {
      type: "text",
      name: "power",
      lable: "Power (W)",
      fullWidth: false,
      required: false,
      placeholder: "Enter power in watts (optional)",
      isNumber: true,
      isNullable: true,
    },
    {
      type: "text",
      name: "fps",
      lable: "FPS",
      fullWidth: false,
      required: false,
      placeholder: "Enter FPS (optional)",
      isNumber: true,
      isNullable: true,
    },
    {
      type: "text",
      name: "soundOutput",
      lable: "Sound Output (W)",
      fullWidth: false,
      required: false,
      placeholder: "Enter sound output in watts (optional)",
      isNumber: true,
      isNullable: true,
    },
    {
      type: "text",
      name: "screenSize",
      lable: "Screen Size (inches)",
      fullWidth: false,
      required: false,
      placeholder: "Enter screen size (optional)",
      isNumber: true,
      isNullable: true,
    },
    {
      type: "quantity",
      name: "stock",
      lable: "Stock",
      fullWidth: false,
      required: false,
      placeholder: "Enter available stock (optional)",
    },
    {
      type: "TextArea",
      name: "description",
      lable: "Description",
      fullWidth: true,
      required: true,
      placeholder: "Enter product description",
    },
    {
      type: "image",
      name: "image",
      lable: "Image URL",
      fullWidth: false,
      required: true,
      placeholder: "Enter image URL",
    },
  ];
