export const colors: string[] = [
  "silver",
  "white",
  "sand gold",
  "Blue",
  "Black",
  "Lavender",
  "gray",
  "Burgundy",
  "steel blue",
  "Smoky Teal",
  "Deep Purple",
  "Golden",
  "Green",
  "Noir Black",
  "Meteorite Black",
  "Aqua Green",
  "Matte Black",
  "Taupe",
  "Pink",
  "dark steel silver",
  "carbon silver",
  "Ceramic Black",
  "Pebble Grey",
  "Metallic Grey",
  "Dark Iron Gray",
  "ceremic black",
  "steel grey",
];
