export type productsType = {
  _id: string;
  productId: number;
  title: string;
  image: string;
  price: number;
  description: string;
  brand: string;
  model: string;
  color?: string | null;
  size?: string | null;
  category: string;
  discount: number;
  stock: number;
  createdAt: string;
  updatedAt: string;
  rating: number;
  sold: number;
  ram?: string | null;
  power?: number | null;
  fps?: number | null;
  soundOutput?: number | null;
  screenSize?: number | null;
};
